spring:
  application:
    name: pdf_extratct
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true

  # Upload 10GB
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
    session:
      tracking-modes: cookie

  # Storage filesystem
  storage:
    location: ./uploads/


  ai:
    vertex:
      ai:
        gemini:
          project-id: "iotska121"
          location: "us-central1"
          chat:
            options:
              model: "gemini-2.5-flash"
              temperature: 0.1

# Server
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10GB
    max-swallow-size: 10GB

# Logs DEBUG Vertex
logging:
  level:
    com.example.pdf_extratct: DEBUG
    org.springframework.ai: DEBUG

