spring:
  application:
    name: pdf_extratct

    threads:
      virtual:
        enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: Y6e93GWCcuwTapQt
      timeout: 60000

    mongodb:
      uri: mongodb://app_user:SB1hd18x5C43NupQ@195.35.19.80:27017/pdf_extract_logs?authSource=admin

#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:8001/postgres
    username: postgres
    password: aea0d89357af91b3775c7ca4d2a99704
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 870141349909-8qk4rrg4jtm2b9p6mkpmls4et9lnv4rt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
    session:
      tracking-modes: cookie

  storage:
    location: ./uploads/

  ai:
    vertex:
      ai:
        gemini:
          project-id: "iotska121"
          location: "us-central1"
          chat:
            options:
              model: "gemini-2.5-flash"
              temperature: 0.1

  profiles:
    active: dev

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10GB
    max-swallow-size: 10GB

jwt:
  secret: YsZQUtmOPQ/EY0Eba+0CLUQJOA4+mpkHqQDHnA0w6Uo=
  expiration: 86400000

logging:
  level:
    com.example.pdf_extratct: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.data.mongodb: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

api:
  v1:
    mercadopago-access-token-vendedor: TEST-5346233072327713-022100-af3ebec84e85c7d265f7b5151a6fb96b-3213929116
    mercadopago-notification-url: https://aristocratically-inaccessible-lucien.ngrok-free.dev/api/v1/webhooks/mercadopago
